highlighter: rouge
permalink: /blog/:year/:month/:title/
baseurl: /
url: https://s.joelverhagen.com
destination: _stage
attachmentdir: attachments
comments: true
exclude: 
- categories.yml
relative_permalinks: false
markdown: kramdown
