pygments: true
permalink: /blog/:year/:month/:title
baseurl: /
url: http://s.joelverhagen.com
destination: _stage
attachmentdir: attachments
comments: true
exclude: 
- categories.yml
relative_permalinks: false
markdown: redcarpet
